/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import napakalaki.BadConsequence;

/**
 *
 * @author juane
 */
public class BadConsequenceView extends javax.swing.JPanel {
    BadConsequence bad_model;
    /**
     * Creates new form BadConsequenceView
     */
    public BadConsequenceView() {
        initComponents();
    }

    public void setBad(BadConsequence p_bad){
        bad_model= p_bad;
        
        this.ind_descr_bad.setText(bad_model.getText());
        this.ind_levels_bad.setText(Integer.toString(bad_model.getLevels()));
        
        repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l_tittle_bad = new javax.swing.JLabel();
        l_descripcion = new javax.swing.JLabel();
        ind_descr_bad = new javax.swing.JTextField();
        l_levels_bad = new javax.swing.JLabel();
        ind_levels_bad = new javax.swing.JTextField();

        l_tittle_bad.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        l_tittle_bad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_tittle_bad.setText("BAD CONSEQUENCE");

        l_descripcion.setText("Descripcion:");

        l_levels_bad.setText("Niveles que perderás:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(l_tittle_bad)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(l_descripcion)
                            .addGap(18, 18, 18)
                            .addComponent(ind_descr_bad, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(l_levels_bad)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ind_levels_bad, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_tittle_bad)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ind_descr_bad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(l_levels_bad)
                    .addComponent(ind_levels_bad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ind_descr_bad;
    private javax.swing.JTextField ind_levels_bad;
    private javax.swing.JLabel l_descripcion;
    private javax.swing.JLabel l_levels_bad;
    private javax.swing.JLabel l_tittle_bad;
    // End of variables declaration//GEN-END:variables
}
