/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import napakalaki.Monster;

/**
 *
 * @author juane
 */
public class MonsterView extends javax.swing.JPanel {
    Monster monster_model;
    /**
     * Creates new form MonsterView
     */
    public MonsterView() {
        initComponents();
    }

    public void setMonster(Monster p_mons){
        monster_model= p_mons;
        
        this.ind_name_monster.setText("<html>"+monster_model.getName()+"</html>");
        this.ind_level_monster.setText(Integer.toString(monster_model.getCombatLevel()));
        
        this.badConsequenceView1.setBad(monster_model.getBadConsequence());
        this.prizeView1.setPrize(monster_model.getPrize());
        repaint();
    }
    /*
    public void HideMonster ()
    {
        jPanel2.setVisible(false);
        jPanel1.setVisible(false);
        monsterBc.setVisible(false);
        
        repaint();
    }
    
    public void ShowMonster ()
    {
        jPanel2.setVisible(true);
        jPanel1.setVisible(true);
        monsterBc.setVisible(true);
        
        repaint();
    }
    */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_prize_monster = new javax.swing.JPanel();
        prizeView1 = new GUI.PrizeView();
        pan_bad_monster = new javax.swing.JPanel();
        badConsequenceView1 = new GUI.BadConsequenceView();
        pane_inf_monster = new javax.swing.JPanel();
        l_name_monster = new javax.swing.JLabel();
        l_level_monster = new javax.swing.JLabel();
        ind_level_monster = new javax.swing.JLabel();
        ind_name_monster = new javax.swing.JLabel();

        panel_prize_monster.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panel_prize_monsterLayout = new javax.swing.GroupLayout(panel_prize_monster);
        panel_prize_monster.setLayout(panel_prize_monsterLayout);
        panel_prize_monsterLayout.setHorizontalGroup(
            panel_prize_monsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_prize_monsterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(prizeView1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panel_prize_monsterLayout.setVerticalGroup(
            panel_prize_monsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_prize_monsterLayout.createSequentialGroup()
                .addComponent(prizeView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pan_bad_monster.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pan_bad_monsterLayout = new javax.swing.GroupLayout(pan_bad_monster);
        pan_bad_monster.setLayout(pan_bad_monsterLayout);
        pan_bad_monsterLayout.setHorizontalGroup(
            pan_bad_monsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_bad_monsterLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(badConsequenceView1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pan_bad_monsterLayout.setVerticalGroup(
            pan_bad_monsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_bad_monsterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(badConsequenceView1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pane_inf_monster.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        l_name_monster.setText("Nombre: ");

        l_level_monster.setText("Nivel de combate: ");

        ind_name_monster.setText("jLabel1");

        javax.swing.GroupLayout pane_inf_monsterLayout = new javax.swing.GroupLayout(pane_inf_monster);
        pane_inf_monster.setLayout(pane_inf_monsterLayout);
        pane_inf_monsterLayout.setHorizontalGroup(
            pane_inf_monsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_inf_monsterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pane_inf_monsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pane_inf_monsterLayout.createSequentialGroup()
                        .addComponent(l_name_monster, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ind_name_monster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(91, 91, 91))
                    .addGroup(pane_inf_monsterLayout.createSequentialGroup()
                        .addComponent(l_level_monster)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ind_level_monster, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pane_inf_monsterLayout.setVerticalGroup(
            pane_inf_monsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_inf_monsterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pane_inf_monsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_name_monster, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(ind_name_monster))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pane_inf_monsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_level_monster, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ind_level_monster, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pan_bad_monster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pane_inf_monster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_prize_monster, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pane_inf_monster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_prize_monster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pan_bad_monster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.BadConsequenceView badConsequenceView1;
    private javax.swing.JLabel ind_level_monster;
    private javax.swing.JLabel ind_name_monster;
    private javax.swing.JLabel l_level_monster;
    private javax.swing.JLabel l_name_monster;
    private javax.swing.JPanel pan_bad_monster;
    private javax.swing.JPanel pane_inf_monster;
    private javax.swing.JPanel panel_prize_monster;
    private GUI.PrizeView prizeView1;
    // End of variables declaration//GEN-END:variables
}
