/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.ArrayList;
import napakalaki.CardDealer;
import napakalaki.Monster;
import napakalaki.Napakalaki;
import napakalaki.Player;

/**
 *
 * @author adrianprodri
 */
public class NapakalakiView extends javax.swing.JFrame {
    private Napakalaki napakalakiModel;
    
    
    public void setNapakalaki(Napakalaki a){
        napakalakiModel = a;
        
        this.playerView1.setNapakalaki(a);
        this.playerView1.setPlayer(napakalakiModel.getCurrentPlayer());
        this.monsterView2.setMonster(napakalakiModel.getCurrentMonster());
        repaint();
    }

    /**
     * Creates new form NapakalakiView
     */
    public NapakalakiView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_currPlayer_nap = new javax.swing.JPanel();
        playerView1 = new GUI.PlayerView();
        monster_panel = new javax.swing.JPanel();
        monsterView2 = new GUI.MonsterView();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NAPAKALAKI GAME");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1280, 700));

        p_currPlayer_nap.setBorder(javax.swing.BorderFactory.createTitledBorder("PLAYER"));

        javax.swing.GroupLayout p_currPlayer_napLayout = new javax.swing.GroupLayout(p_currPlayer_nap);
        p_currPlayer_nap.setLayout(p_currPlayer_napLayout);
        p_currPlayer_napLayout.setHorizontalGroup(
            p_currPlayer_napLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_currPlayer_napLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playerView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p_currPlayer_napLayout.setVerticalGroup(
            p_currPlayer_napLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_currPlayer_napLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(playerView1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        monster_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("MONSTER"));

        javax.swing.GroupLayout monster_panelLayout = new javax.swing.GroupLayout(monster_panel);
        monster_panel.setLayout(monster_panelLayout);
        monster_panelLayout.setHorizontalGroup(
            monster_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(monster_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(monsterView2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        monster_panelLayout.setVerticalGroup(
            monster_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(monster_panelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(monsterView2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_currPlayer_nap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(monster_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p_currPlayer_nap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(monster_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void showView(){
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.MonsterView monsterView2;
    private javax.swing.JPanel monster_panel;
    private javax.swing.JPanel p_currPlayer_nap;
    private GUI.PlayerView playerView1;
    // End of variables declaration//GEN-END:variables
}
