package GUI;


import napakalaki.Treasure;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author adrianprodri
 */
public class TreasureView extends javax.swing.JPanel {
    
    private Treasure treasureModel;
    
    public void setTreasure(Treasure t){
        treasureModel = t;
        this.ind_name_treasure.setText(treasureModel.getName());
        this.ind_level_treasure.setText(Integer.toString(treasureModel.getBonus()));
        this.ind_type_treasure.setText(treasureModel.getType().toString());
        repaint();
    }

    /**
     * Creates new form TreasureView
     */
    public TreasureView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ind_level_treasure = new javax.swing.JLabel();
        ind_name_treasure = new javax.swing.JLabel();
        ind_type_treasure = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ind_level_treasure.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        ind_level_treasure.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ind_level_treasure.setText("5");
        ind_level_treasure.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ind_name_treasure.setText("jLabel1");
        ind_name_treasure.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ind_type_treasure.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ind_type_treasure.setText("HELMET");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ind_type_treasure, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(ind_level_treasure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ind_name_treasure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(ind_name_treasure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ind_level_treasure, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ind_type_treasure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ind_level_treasure;
    private javax.swing.JLabel ind_name_treasure;
    private javax.swing.JLabel ind_type_treasure;
    // End of variables declaration//GEN-END:variables
}
